### PR TITLE
Adding -mjs.js build to support polymer-cli

### PR DESCRIPTION
**Pull request by cloudily**

### CODE REVIEW

**Comment by pladaria** [comment]
Hi, thank you for this PR

Before accepting it I need some more context. Why do you need this?

How does `polymer-cli` know about the newly created artifact? It is not listed in `package.json`. 
It is this following some kind of naming convention?

Thanks

**Comment by cloudily** [comment]
Hi @pladaria,

The `mjs` extension has not been formalized yet.  It is currently recognized by node, but not by some build tools.  For example, the polymer-cli throws an error with the unrecognized mjs extension.  This is to provide build tools a way to interpret these files as they relate to ES imports.  Please let me know if you have any further questions.

**Comment by pladaria** [comment]
All clear! Thank you for your explanation

**Comment by pladaria** [comment]
published 4.1.10 with that change

**Comment by cloudily** [comment]
Thanks, @pladaria

**Pull request merged**
