### PR TITLE
Retry reconnect if connection timeouts while retrying (Should fix #48)

### LINKED ISSUE #48: Doesn't work for GDAX (node)
The module doesn't manage to stay connected to the [GDAX] crypto data feed:

```js
const WebSocket = require('ws');
const ReconnectingWebSocket = require('reconnecting-websocket');
const rws = new ReconnectingWebSocket('wss://ws-feed.gdax.com', [], {
  constructor: WebSocket,
  debug: true,
});

let lastPointTimestamp = new Date();
setInterval(() => {
  if (Date.now() - lastPointTimestamp > 60 * 1000)
    // No data in the past minute since we got called
    console.warn('Got disconnected and did not reconnect');
}, 60 * 1000);

function handleData(data) {
  lastPointTimestamp = Date.now();
  console.log(data.price);
}

rws.on('open', () => {
  rws.send(JSON.stringify({
    type: 'subscribe',
    product_ids: ['BTC-USD'],
    channels: ['matches'],
  }));
});
rws.on('message', data => handleData(JSON.parse(data)));
rws.on('error', err => {
  console.error('ON ERROR -', err);
});

```

The log shows this:

```
ON ERROR - { Error: read ECONNRESET
    at _errnoException (util.js:1003:13)
    at TLSWrap.onread (net.js:620:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
RWS: handleClose { shouldRetry: true }
RWS: retries count: 1
RWS: handleClose - reconnectDelay: 2043.1049894719274
RWS: connect
RWS: bypass properties
RWS: timeout
```

### PR DESCRIPTION
**Pull request by kinsi55**
I hardly ever work with Typescript so i hope this is correct :P

### CODE REVIEW

**Comment by pladaria** [comment]
Hi, can you please check the commented solution in #48?

**Comment by kinsi55** [comment]
Is it fully compatible to the default WS implementation, as in, being a 1:1 replacible?

**Comment by pladaria** [comment]
@kinsi55 yes, it should. If not, please open an issue

**Comment by kinsi55** [comment]
Alright, i'll give it a try later on (Im just going to assume that that would fix it pretty much). Possibly, if WS is incompatible you should error out if the user passes it, or alterantively ofc make it work with WS :D

**Comment by kinsi55** [comment]
Forgot to get back. Yes using the `html5-websocket` module does work. Maybe native WS support should be a thing to consider.

**Pull request closed without merging**
